# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20160221_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='imdb_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='popularity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
    ]
